package com.ezmall.model;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.ID
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.NO
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.USERNAME
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.PASSWORD
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.COMPANY
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.LINKMAN
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.TEL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.MOBILE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.EMAIL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.ADDRESS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.TYPE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.STATUS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin.CREATE_DATE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.ID
     *
     * @return the value of tbl_admin.ID
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.ID
     *
     * @param id the value for tbl_admin.ID
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.NO
     *
     * @return the value of tbl_admin.NO
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.NO
     *
     * @param no the value for tbl_admin.NO
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.USERNAME
     *
     * @return the value of tbl_admin.USERNAME
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.USERNAME
     *
     * @param username the value for tbl_admin.USERNAME
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.PASSWORD
     *
     * @return the value of tbl_admin.PASSWORD
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.PASSWORD
     *
     * @param password the value for tbl_admin.PASSWORD
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.COMPANY
     *
     * @return the value of tbl_admin.COMPANY
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.COMPANY
     *
     * @param company the value for tbl_admin.COMPANY
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.LINKMAN
     *
     * @return the value of tbl_admin.LINKMAN
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.LINKMAN
     *
     * @param linkman the value for tbl_admin.LINKMAN
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.TEL
     *
     * @return the value of tbl_admin.TEL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.TEL
     *
     * @param tel the value for tbl_admin.TEL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.MOBILE
     *
     * @return the value of tbl_admin.MOBILE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.MOBILE
     *
     * @param mobile the value for tbl_admin.MOBILE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.EMAIL
     *
     * @return the value of tbl_admin.EMAIL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.EMAIL
     *
     * @param email the value for tbl_admin.EMAIL
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.ADDRESS
     *
     * @return the value of tbl_admin.ADDRESS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.ADDRESS
     *
     * @param address the value for tbl_admin.ADDRESS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.TYPE
     *
     * @return the value of tbl_admin.TYPE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.TYPE
     *
     * @param type the value for tbl_admin.TYPE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.STATUS
     *
     * @return the value of tbl_admin.STATUS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.STATUS
     *
     * @param status the value for tbl_admin.STATUS
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin.CREATE_DATE
     *
     * @return the value of tbl_admin.CREATE_DATE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin.CREATE_DATE
     *
     * @param createDate the value for tbl_admin.CREATE_DATE
     *
     * @mbggenerated Fri Aug 29 11:20:55 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}