package com.ezmall.model;

public class AdminRoleRp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_role_rp.ID
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_role_rp.user_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_admin_role_rp.role_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_role_rp.ID
     *
     * @return the value of tbl_admin_role_rp.ID
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_role_rp.ID
     *
     * @param id the value for tbl_admin_role_rp.ID
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_role_rp.user_id
     *
     * @return the value of tbl_admin_role_rp.user_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_role_rp.user_id
     *
     * @param userId the value for tbl_admin_role_rp.user_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_admin_role_rp.role_id
     *
     * @return the value of tbl_admin_role_rp.role_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_admin_role_rp.role_id
     *
     * @param roleId the value for tbl_admin_role_rp.role_id
     *
     * @mbggenerated Thu Jul 03 21:55:57 CST 2014
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}