package com.ezmall.model;

public class CategoryPropRp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_prop_rp.ID
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_prop_rp.CATEGORY_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_category_prop_rp.PROPITEM_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    private String propitemNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_prop_rp.ID
     *
     * @return the value of tbl_category_prop_rp.ID
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_prop_rp.ID
     *
     * @param id the value for tbl_category_prop_rp.ID
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_prop_rp.CATEGORY_NO
     *
     * @return the value of tbl_category_prop_rp.CATEGORY_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_prop_rp.CATEGORY_NO
     *
     * @param categoryNo the value for tbl_category_prop_rp.CATEGORY_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_category_prop_rp.PROPITEM_NO
     *
     * @return the value of tbl_category_prop_rp.PROPITEM_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public String getPropitemNo() {
        return propitemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_category_prop_rp.PROPITEM_NO
     *
     * @param propitemNo the value for tbl_category_prop_rp.PROPITEM_NO
     *
     * @mbggenerated Wed Jun 18 15:59:44 CST 2014
     */
    public void setPropitemNo(String propitemNo) {
        this.propitemNo = propitemNo == null ? null : propitemNo.trim();
    }
}