package com.ezmall.model;

import java.util.Date;

public class FriendOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.ID
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.MEMBER_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.FRIEND_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private String friendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.STATUS
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_friend_order.CREATE_DATE
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.ID
     *
     * @return the value of tbl_friend_order.ID
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.ID
     *
     * @param id the value for tbl_friend_order.ID
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.ORDER_NO
     *
     * @return the value of tbl_friend_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.ORDER_NO
     *
     * @param orderNo the value for tbl_friend_order.ORDER_NO
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.MEMBER_NAME
     *
     * @return the value of tbl_friend_order.MEMBER_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.MEMBER_NAME
     *
     * @param memberName the value for tbl_friend_order.MEMBER_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.FRIEND_NAME
     *
     * @return the value of tbl_friend_order.FRIEND_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public String getFriendName() {
        return friendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.FRIEND_NAME
     *
     * @param friendName the value for tbl_friend_order.FRIEND_NAME
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setFriendName(String friendName) {
        this.friendName = friendName == null ? null : friendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.STATUS
     *
     * @return the value of tbl_friend_order.STATUS
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.STATUS
     *
     * @param status the value for tbl_friend_order.STATUS
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_friend_order.CREATE_DATE
     *
     * @return the value of tbl_friend_order.CREATE_DATE
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_friend_order.CREATE_DATE
     *
     * @param createDate the value for tbl_friend_order.CREATE_DATE
     *
     * @mbggenerated Mon Jul 21 09:50:56 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}