package com.ezmall.model;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.ID
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String brandNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String categoryStruct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String categoryStructName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String merchantCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Double sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GIFT_SCORE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Integer giftScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Double expressPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String styleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String specName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.YEAR
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.UNIT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.PROVINCE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CITY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String goodsPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.STATUS
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    private String goodsDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.ID
     *
     * @return the value of tbl_goods_info.ID
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.ID
     *
     * @param id the value for tbl_goods_info.ID
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.NO
     *
     * @return the value of tbl_goods_info.NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.NO
     *
     * @param no the value for tbl_goods_info.NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.NAME
     *
     * @return the value of tbl_goods_info.NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.NAME
     *
     * @param name the value for tbl_goods_info.NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.BRAND_NO
     *
     * @return the value of tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getBrandNo() {
        return brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.BRAND_NO
     *
     * @param brandNo the value for tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setBrandNo(String brandNo) {
        this.brandNo = brandNo == null ? null : brandNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.BRAND_NAME
     *
     * @return the value of tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.BRAND_NAME
     *
     * @param brandName the value for tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_NO
     *
     * @return the value of tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_NO
     *
     * @param categoryNo the value for tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @return the value of tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getCategoryStruct() {
        return categoryStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @param categoryStruct the value for tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCategoryStruct(String categoryStruct) {
        this.categoryStruct = categoryStruct == null ? null : categoryStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @return the value of tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getCategoryStructName() {
        return categoryStructName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @param categoryStructName the value for tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCategoryStructName(String categoryStructName) {
        this.categoryStructName = categoryStructName == null ? null : categoryStructName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MERCHANT_NAME
     *
     * @return the value of tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MERCHANT_NAME
     *
     * @param merchantName the value for tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @return the value of tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getMerchantCompany() {
        return merchantCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @param merchantCompany the value for tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setMerchantCompany(String merchantCompany) {
        this.merchantCompany = merchantCompany == null ? null : merchantCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.COST_PRICE
     *
     * @return the value of tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.COST_PRICE
     *
     * @param costPrice the value for tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SELL_PRICE
     *
     * @return the value of tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SELL_PRICE
     *
     * @param sellPrice the value for tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GIFT_SCORE
     *
     * @return the value of tbl_goods_info.GIFT_SCORE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Integer getGiftScore() {
        return giftScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GIFT_SCORE
     *
     * @param giftScore the value for tbl_goods_info.GIFT_SCORE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setGiftScore(Integer giftScore) {
        this.giftScore = giftScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MARKET_PRICE
     *
     * @return the value of tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MARKET_PRICE
     *
     * @param marketPrice the value for tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @return the value of tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Double getExpressPrice() {
        return expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @param expressPrice the value for tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setExpressPrice(Double expressPrice) {
        this.expressPrice = expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @return the value of tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @param currencyType the value for tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.STYLE_NO
     *
     * @return the value of tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getStyleNo() {
        return styleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.STYLE_NO
     *
     * @param styleNo the value for tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setStyleNo(String styleNo) {
        this.styleNo = styleNo == null ? null : styleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SPEC_NAME
     *
     * @return the value of tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SPEC_NAME
     *
     * @param specName the value for tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.YEAR
     *
     * @return the value of tbl_goods_info.YEAR
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.YEAR
     *
     * @param year the value for tbl_goods_info.YEAR
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.UNIT
     *
     * @return the value of tbl_goods_info.UNIT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.UNIT
     *
     * @param unit the value for tbl_goods_info.UNIT
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.PROVINCE
     *
     * @return the value of tbl_goods_info.PROVINCE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.PROVINCE
     *
     * @param province the value for tbl_goods_info.PROVINCE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CITY
     *
     * @return the value of tbl_goods_info.CITY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CITY
     *
     * @param city the value for tbl_goods_info.CITY
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GOODS_PICTURE
     *
     * @return the value of tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getGoodsPicture() {
        return goodsPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GOODS_PICTURE
     *
     * @param goodsPicture the value for tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setGoodsPicture(String goodsPicture) {
        this.goodsPicture = goodsPicture == null ? null : goodsPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @return the value of tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @param supplierCode the value for tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.STATUS
     *
     * @return the value of tbl_goods_info.STATUS
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.STATUS
     *
     * @param status the value for tbl_goods_info.STATUS
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.VALID_FLAG
     *
     * @return the value of tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.VALID_FLAG
     *
     * @param validFlag the value for tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CREATE_DATE
     *
     * @return the value of tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CREATE_DATE
     *
     * @param createDate the value for tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.UPDATE_DATE
     *
     * @return the value of tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.UPDATE_DATE
     *
     * @param updateDate the value for tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GOODS_DESC
     *
     * @return the value of tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GOODS_DESC
     *
     * @param goodsDesc the value for tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Thu Oct 23 10:55:51 CST 2014
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }
}