package com.ezmall.model;

import java.util.Date;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String brandNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String categoryNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String categoryStruct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String categoryStructName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String merchantCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Double sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GIVE_SCORE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Integer giveScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Double marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Double expressPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String styleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String specName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.YEAR
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.UNIT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.COUNTRY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.COUNTRY_INDEX
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String countryIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CITY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.MALL
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String mall;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String goodsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String goodsPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_LINK
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_DOMAIN
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String supplierCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.STATUS
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_COL_1
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdCol1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_goods_info.THIRD_COL_2
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    private String thirdCol2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.ID
     *
     * @return the value of tbl_goods_info.ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.ID
     *
     * @param id the value for tbl_goods_info.ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.NO
     *
     * @return the value of tbl_goods_info.NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.NO
     *
     * @param no the value for tbl_goods_info.NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.NAME
     *
     * @return the value of tbl_goods_info.NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.NAME
     *
     * @param name the value for tbl_goods_info.NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.BRAND_NO
     *
     * @return the value of tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getBrandNo() {
        return brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.BRAND_NO
     *
     * @param brandNo the value for tbl_goods_info.BRAND_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setBrandNo(String brandNo) {
        this.brandNo = brandNo == null ? null : brandNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.BRAND_NAME
     *
     * @return the value of tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.BRAND_NAME
     *
     * @param brandName the value for tbl_goods_info.BRAND_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_NO
     *
     * @return the value of tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCategoryNo() {
        return categoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_NO
     *
     * @param categoryNo the value for tbl_goods_info.CATEGORY_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCategoryNo(String categoryNo) {
        this.categoryNo = categoryNo == null ? null : categoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @return the value of tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCategoryStruct() {
        return categoryStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_STRUCT
     *
     * @param categoryStruct the value for tbl_goods_info.CATEGORY_STRUCT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCategoryStruct(String categoryStruct) {
        this.categoryStruct = categoryStruct == null ? null : categoryStruct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @return the value of tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCategoryStructName() {
        return categoryStructName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @param categoryStructName the value for tbl_goods_info.CATEGORY_STRUCT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCategoryStructName(String categoryStructName) {
        this.categoryStructName = categoryStructName == null ? null : categoryStructName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MERCHANT_NAME
     *
     * @return the value of tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MERCHANT_NAME
     *
     * @param merchantName the value for tbl_goods_info.MERCHANT_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @return the value of tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getMerchantCompany() {
        return merchantCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MERCHANT_COMPANY
     *
     * @param merchantCompany the value for tbl_goods_info.MERCHANT_COMPANY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setMerchantCompany(String merchantCompany) {
        this.merchantCompany = merchantCompany == null ? null : merchantCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.COST_PRICE
     *
     * @return the value of tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.COST_PRICE
     *
     * @param costPrice the value for tbl_goods_info.COST_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SELL_PRICE
     *
     * @return the value of tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SELL_PRICE
     *
     * @param sellPrice the value for tbl_goods_info.SELL_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GIVE_SCORE
     *
     * @return the value of tbl_goods_info.GIVE_SCORE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Integer getGiveScore() {
        return giveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GIVE_SCORE
     *
     * @param giveScore the value for tbl_goods_info.GIVE_SCORE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setGiveScore(Integer giveScore) {
        this.giveScore = giveScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MARKET_PRICE
     *
     * @return the value of tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Double getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MARKET_PRICE
     *
     * @param marketPrice the value for tbl_goods_info.MARKET_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setMarketPrice(Double marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @return the value of tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Double getExpressPrice() {
        return expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.EXPRESS_PRICE
     *
     * @param expressPrice the value for tbl_goods_info.EXPRESS_PRICE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setExpressPrice(Double expressPrice) {
        this.expressPrice = expressPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @return the value of tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CURRENCY_TYPE
     *
     * @param currencyType the value for tbl_goods_info.CURRENCY_TYPE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.STYLE_NO
     *
     * @return the value of tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getStyleNo() {
        return styleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.STYLE_NO
     *
     * @param styleNo the value for tbl_goods_info.STYLE_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setStyleNo(String styleNo) {
        this.styleNo = styleNo == null ? null : styleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SPEC_NAME
     *
     * @return the value of tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SPEC_NAME
     *
     * @param specName the value for tbl_goods_info.SPEC_NAME
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setSpecName(String specName) {
        this.specName = specName == null ? null : specName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.YEAR
     *
     * @return the value of tbl_goods_info.YEAR
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.YEAR
     *
     * @param year the value for tbl_goods_info.YEAR
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.UNIT
     *
     * @return the value of tbl_goods_info.UNIT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.UNIT
     *
     * @param unit the value for tbl_goods_info.UNIT
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.COUNTRY
     *
     * @return the value of tbl_goods_info.COUNTRY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.COUNTRY
     *
     * @param country the value for tbl_goods_info.COUNTRY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.COUNTRY_INDEX
     *
     * @return the value of tbl_goods_info.COUNTRY_INDEX
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCountryIndex() {
        return countryIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.COUNTRY_INDEX
     *
     * @param countryIndex the value for tbl_goods_info.COUNTRY_INDEX
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCountryIndex(String countryIndex) {
        this.countryIndex = countryIndex == null ? null : countryIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CITY
     *
     * @return the value of tbl_goods_info.CITY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CITY
     *
     * @param city the value for tbl_goods_info.CITY
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.MALL
     *
     * @return the value of tbl_goods_info.MALL
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getMall() {
        return mall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.MALL
     *
     * @param mall the value for tbl_goods_info.MALL
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setMall(String mall) {
        this.mall = mall == null ? null : mall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GOODS_DESC
     *
     * @return the value of tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GOODS_DESC
     *
     * @param goodsDesc the value for tbl_goods_info.GOODS_DESC
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.GOODS_PICTURE
     *
     * @return the value of tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getGoodsPicture() {
        return goodsPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.GOODS_PICTURE
     *
     * @param goodsPicture the value for tbl_goods_info.GOODS_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setGoodsPicture(String goodsPicture) {
        this.goodsPicture = goodsPicture == null ? null : goodsPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_ID
     *
     * @return the value of tbl_goods_info.THIRD_ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdId() {
        return thirdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_ID
     *
     * @param thirdId the value for tbl_goods_info.THIRD_ID
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdId(String thirdId) {
        this.thirdId = thirdId == null ? null : thirdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_NO
     *
     * @return the value of tbl_goods_info.THIRD_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdNo() {
        return thirdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_NO
     *
     * @param thirdNo the value for tbl_goods_info.THIRD_NO
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdNo(String thirdNo) {
        this.thirdNo = thirdNo == null ? null : thirdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_LINK
     *
     * @return the value of tbl_goods_info.THIRD_LINK
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdLink() {
        return thirdLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_LINK
     *
     * @param thirdLink the value for tbl_goods_info.THIRD_LINK
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdLink(String thirdLink) {
        this.thirdLink = thirdLink == null ? null : thirdLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_PICTURE
     *
     * @return the value of tbl_goods_info.THIRD_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdPicture() {
        return thirdPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_PICTURE
     *
     * @param thirdPicture the value for tbl_goods_info.THIRD_PICTURE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdPicture(String thirdPicture) {
        this.thirdPicture = thirdPicture == null ? null : thirdPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_DOMAIN
     *
     * @return the value of tbl_goods_info.THIRD_DOMAIN
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdDomain() {
        return thirdDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_DOMAIN
     *
     * @param thirdDomain the value for tbl_goods_info.THIRD_DOMAIN
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdDomain(String thirdDomain) {
        this.thirdDomain = thirdDomain == null ? null : thirdDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @return the value of tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getSupplierCode() {
        return supplierCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.SUPPLIER_CODE
     *
     * @param supplierCode the value for tbl_goods_info.SUPPLIER_CODE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setSupplierCode(String supplierCode) {
        this.supplierCode = supplierCode == null ? null : supplierCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.STATUS
     *
     * @return the value of tbl_goods_info.STATUS
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.STATUS
     *
     * @param status the value for tbl_goods_info.STATUS
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.VALID_FLAG
     *
     * @return the value of tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.VALID_FLAG
     *
     * @param validFlag the value for tbl_goods_info.VALID_FLAG
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.CREATE_DATE
     *
     * @return the value of tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.CREATE_DATE
     *
     * @param createDate the value for tbl_goods_info.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.UPDATE_DATE
     *
     * @return the value of tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.UPDATE_DATE
     *
     * @param updateDate the value for tbl_goods_info.UPDATE_DATE
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_COL_1
     *
     * @return the value of tbl_goods_info.THIRD_COL_1
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdCol1() {
        return thirdCol1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_COL_1
     *
     * @param thirdCol1 the value for tbl_goods_info.THIRD_COL_1
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdCol1(String thirdCol1) {
        this.thirdCol1 = thirdCol1 == null ? null : thirdCol1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_goods_info.THIRD_COL_2
     *
     * @return the value of tbl_goods_info.THIRD_COL_2
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public String getThirdCol2() {
        return thirdCol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_goods_info.THIRD_COL_2
     *
     * @param thirdCol2 the value for tbl_goods_info.THIRD_COL_2
     *
     * @mbggenerated Sun Aug 03 18:00:00 CST 2014
     */
    public void setThirdCol2(String thirdCol2) {
        this.thirdCol2 = thirdCol2 == null ? null : thirdCol2.trim();
    }
}