package com.ezmall.model;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.ID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.USERNAME
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.PASSWORD
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.LINKMAN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.EMAIL
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.ADDRESS
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.MOBILE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.WB_UID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String wbUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.WB_TOKEN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String wbToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.LOGIN_TYPE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private String loginType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.UPDATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_member.CREATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.ID
     *
     * @return the value of tbl_member.ID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.ID
     *
     * @param id the value for tbl_member.ID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.USERNAME
     *
     * @return the value of tbl_member.USERNAME
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.USERNAME
     *
     * @param username the value for tbl_member.USERNAME
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.PASSWORD
     *
     * @return the value of tbl_member.PASSWORD
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.PASSWORD
     *
     * @param password the value for tbl_member.PASSWORD
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.LINKMAN
     *
     * @return the value of tbl_member.LINKMAN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.LINKMAN
     *
     * @param linkman the value for tbl_member.LINKMAN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.EMAIL
     *
     * @return the value of tbl_member.EMAIL
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.EMAIL
     *
     * @param email the value for tbl_member.EMAIL
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.ADDRESS
     *
     * @return the value of tbl_member.ADDRESS
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.ADDRESS
     *
     * @param address the value for tbl_member.ADDRESS
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.MOBILE
     *
     * @return the value of tbl_member.MOBILE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.MOBILE
     *
     * @param mobile the value for tbl_member.MOBILE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.WB_UID
     *
     * @return the value of tbl_member.WB_UID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getWbUid() {
        return wbUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.WB_UID
     *
     * @param wbUid the value for tbl_member.WB_UID
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setWbUid(String wbUid) {
        this.wbUid = wbUid == null ? null : wbUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.WB_TOKEN
     *
     * @return the value of tbl_member.WB_TOKEN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getWbToken() {
        return wbToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.WB_TOKEN
     *
     * @param wbToken the value for tbl_member.WB_TOKEN
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setWbToken(String wbToken) {
        this.wbToken = wbToken == null ? null : wbToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.LOGIN_TYPE
     *
     * @return the value of tbl_member.LOGIN_TYPE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.LOGIN_TYPE
     *
     * @param loginType the value for tbl_member.LOGIN_TYPE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.UPDATE_DATE
     *
     * @return the value of tbl_member.UPDATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.UPDATE_DATE
     *
     * @param updateDate the value for tbl_member.UPDATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_member.CREATE_DATE
     *
     * @return the value of tbl_member.CREATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_member.CREATE_DATE
     *
     * @param createDate the value for tbl_member.CREATE_DATE
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}