package com.ezmall.model;

import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.ID
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.INSIDE_CODE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private String insideCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.SIZE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.GOODS_NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private String goodsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_product_info.CREATE_DATE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.ID
     *
     * @return the value of tbl_product_info.ID
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.ID
     *
     * @param id the value for tbl_product_info.ID
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.NO
     *
     * @return the value of tbl_product_info.NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.NO
     *
     * @param no the value for tbl_product_info.NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.INSIDE_CODE
     *
     * @return the value of tbl_product_info.INSIDE_CODE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public String getInsideCode() {
        return insideCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.INSIDE_CODE
     *
     * @param insideCode the value for tbl_product_info.INSIDE_CODE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setInsideCode(String insideCode) {
        this.insideCode = insideCode == null ? null : insideCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.SIZE
     *
     * @return the value of tbl_product_info.SIZE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.SIZE
     *
     * @param size the value for tbl_product_info.SIZE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.GOODS_NO
     *
     * @return the value of tbl_product_info.GOODS_NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public String getGoodsNo() {
        return goodsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.GOODS_NO
     *
     * @param goodsNo the value for tbl_product_info.GOODS_NO
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo == null ? null : goodsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_product_info.CREATE_DATE
     *
     * @return the value of tbl_product_info.CREATE_DATE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_product_info.CREATE_DATE
     *
     * @param createDate the value for tbl_product_info.CREATE_DATE
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}