package com.ezmall.model;

import java.util.Date;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_purchase_main.ID
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_purchase_main.NO
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_purchase_main.USERNAME
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_purchase_main.STATUS
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_purchase_main.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_purchase_main.ID
     *
     * @return the value of tbl_purchase_main.ID
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_purchase_main.ID
     *
     * @param id the value for tbl_purchase_main.ID
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_purchase_main.NO
     *
     * @return the value of tbl_purchase_main.NO
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_purchase_main.NO
     *
     * @param no the value for tbl_purchase_main.NO
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_purchase_main.USERNAME
     *
     * @return the value of tbl_purchase_main.USERNAME
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_purchase_main.USERNAME
     *
     * @param username the value for tbl_purchase_main.USERNAME
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_purchase_main.STATUS
     *
     * @return the value of tbl_purchase_main.STATUS
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_purchase_main.STATUS
     *
     * @param status the value for tbl_purchase_main.STATUS
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_purchase_main.CREATE_DATE
     *
     * @return the value of tbl_purchase_main.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_purchase_main.CREATE_DATE
     *
     * @param createDate the value for tbl_purchase_main.CREATE_DATE
     *
     * @mbggenerated Sun Aug 03 21:18:48 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}