package com.ezmall.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.ID
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_name
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_role.role_desc
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.ID
     *
     * @return the value of tbl_role.ID
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.ID
     *
     * @param id the value for tbl_role.ID
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_name
     *
     * @return the value of tbl_role.role_name
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_name
     *
     * @param roleName the value for tbl_role.role_name
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_role.role_desc
     *
     * @return the value of tbl_role.role_desc
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_role.role_desc
     *
     * @param roleDesc the value for tbl_role.role_desc
     *
     * @mbggenerated Thu Jul 03 21:55:09 CST 2014
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }
}