package com.ezmall.mapper;

import com.ezmall.model.Brand;
import com.ezmall.model.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int countByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int deleteByExample(BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    List<Brand> selectByExample(BrandExample example);
    List<Brand> selectByExample(BrandExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    Brand selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int updateByExample(@Param("record") Brand record, @Param("example") BrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_brand_info
     *
     * @mbggenerated Tue Jun 17 22:58:36 CST 2014
     */
    int updateByPrimaryKey(Brand record);
}