package com.ezmall.mapper;

import com.ezmall.model.Friend;
import com.ezmall.model.FriendExample;

import java.util.List;

import com.ezmall.vo.FriendVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    List<Friend> selectByExample(FriendExample example);

    List<Friend> selectByExample(FriendExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    Friend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int updateByExampleSelective(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int updateByExample(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_friend
     *
     * @mbggenerated Sun Jul 13 11:07:31 CST 2014
     */
    int updateByPrimaryKey(Friend record);

    List<FriendVo> getMyFriendVo(@Param("memberUserName") String memberUserName, @Param("status") String status, RowBounds rowBounds);

    List<FriendVo> getBeInviteFriendVo(@Param("memberUserName") String memberUserName, @Param("status") String status, RowBounds rowBounds);
}