package com.ezmall.mapper;

import com.ezmall.model.GoodsPropRp;
import com.ezmall.model.GoodsPropRpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsPropRpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int countByExample(GoodsPropRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int deleteByExample(GoodsPropRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int insert(GoodsPropRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int insertSelective(GoodsPropRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    List<GoodsPropRp> selectByExample(GoodsPropRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    GoodsPropRp selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int updateByExampleSelective(@Param("record") GoodsPropRp record, @Param("example") GoodsPropRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int updateByExample(@Param("record") GoodsPropRp record, @Param("example") GoodsPropRpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int updateByPrimaryKeySelective(GoodsPropRp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_goods_prop_rp
     *
     * @mbggenerated Wed Jun 18 15:57:17 CST 2014
     */
    int updateByPrimaryKey(GoodsPropRp record);
}