package com.ezmall.mapper;

import com.ezmall.model.Member;
import com.ezmall.model.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    List<Member> selectByExample(MemberExample example);
    List<Member> selectByExample(MemberExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    Member selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_member
     *
     * @mbggenerated Wed Jul 09 21:43:36 CST 2014
     */
    int updateByPrimaryKey(Member record);
}