package com.ezmall.mapper;

import com.ezmall.model.Order;
import com.ezmall.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    List<Order> selectByExample(OrderExample example);

    List<Order> selectByExample(OrderExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_main
     *
     * @mbggenerated Sun Jul 06 23:12:35 CST 2014
     */
    int updateByPrimaryKey(Order record);
}