package com.ezmall.mapper;

import com.ezmall.model.Product;
import com.ezmall.model.ProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int countByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int deleteByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    List<Product> selectByExample(ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    Product selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_product_info
     *
     * @mbggenerated Mon Jun 16 21:22:15 CST 2014
     */
    int updateByPrimaryKey(Product record);
}