package com.ezmall.mapper;

import com.ezmall.model.PropItem;
import com.ezmall.model.PropItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PropItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int countByExample(PropItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int deleteByExample(PropItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int insert(PropItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int insertSelective(PropItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    List<PropItem> selectByExample(PropItemExample example);

    List<PropItem> selectByExample(PropItemExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    PropItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int updateByExampleSelective(@Param("record") PropItem record, @Param("example") PropItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int updateByExample(@Param("record") PropItem record, @Param("example") PropItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int updateByPrimaryKeySelective(PropItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_propitem_info
     *
     * @mbggenerated Tue Jun 10 21:31:48 CST 2014
     */
    int updateByPrimaryKey(PropItem record);
}