package com.ezmall.mapper;

import com.ezmall.model.SubOrder;
import com.ezmall.model.SubOrderExample;
import java.util.List;

import com.ezmall.vo.OrderQueryVo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SubOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int countByExample(SubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int deleteByExample(SubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int insert(SubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int insertSelective(SubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    List<SubOrder> selectByExample(SubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    SubOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int updateByExampleSelective(@Param("record") SubOrder record, @Param("example") SubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int updateByExample(@Param("record") SubOrder record, @Param("example") SubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int updateByPrimaryKeySelective(SubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_order_sub
     *
     * @mbggenerated Sun Jun 29 20:39:19 CST 2014
     */
    int updateByPrimaryKey(SubOrder record);

    List<SubOrder> getSubOrderPageData(OrderQueryVo vo,RowBounds rowBounds);

    Integer countSubOrderPageData(OrderQueryVo vo);
}